# Generated by Django 3.1.3 on 2020-11-19 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers_website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='ativo_produto',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='senha',
            field=models.CharField(default='0000000', max_length=12),
        ),
        migrations.AlterField(
            model_name='produto',
            name='quantidade_produto',
            field=models.IntegerField(),
        ),
    ]
