# Generated by Django 3.1.3 on 2020-11-20 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellers_website', '0003_remove_produto_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='imagem_produto',
        ),
    ]
