# Generated by Django 3.1.3 on 2020-11-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers_website', '0004_remove_produto_imagem_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='codigo_produto',
            field=models.IntegerField(default='000000'),
        ),
    ]
