# Generated by Django 3.1.3 on 2020-11-20 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellers_website', '0006_produto_imagem_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='imagem_produto',
        ),
    ]
