# Generated by Django 3.1.3 on 2020-11-20 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellers_website', '0011_auto_20201120_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='imagem_produto',
        ),
    ]
